from __future__ import annotations

import base64
import html
from pathlib import Path

from .storage import SessionStore


class HtmlExporter:
    def __init__(self, root: Path):
        self.root = Path(root)
        self.store = SessionStore(self.root)

    def export(self, session_id: str) -> Path:
        session = self.store.load_session(session_id)
        output_dir = self.root / "exports" / session_id
        output_dir.mkdir(parents=True, exist_ok=True)
        output = output_dir / "evidence-report.html"
        output.write_text(self._render(session), encoding="utf-8")
        return output

    def _render(self, session: dict) -> str:
        metadata = session.get("metadata", {})
        title = metadata.get("activity") or "Panoptix Evidence Report"
        highlights = [event for event in session.get("events", []) if event.get("highlight")]
        highlight_cards = "\n".join(self._render_event(session, event) for event in highlights)
        cards = "\n".join(self._render_event(session, event) for event in session.get("events", []))
        metadata_rows = "\n".join(
            f"<dt>{html.escape(str(key).replace('_', ' ').title())}</dt><dd>{html.escape(str(value))}</dd>"
            for key, value in metadata.items()
            if value
        )
        return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{html.escape(title)}</title>
  <style>
    :root {{ --bg: #101318; --sur: #181d25; --text: #f5f7fa; --muted: #aab3c2; --accent: #4ade80; --danger: #ef233c; }}
    body {{ margin: 0; font-family: Arial, sans-serif; background: var(--bg); color: var(--text); }}
    header {{ padding: 28px 36px; border-bottom: 1px solid #2a313d; }}
    main {{ max-width: 1120px; margin: 0 auto; padding: 28px; }}
    dl {{ display: grid; grid-template-columns: 180px 1fr; gap: 8px 18px; color: var(--muted); }}
    dt {{ font-weight: 700; color: var(--text); }}
    .event {{ background: var(--sur); border: 1px solid #2a313d; border-radius: 8px; margin: 24px 0; overflow: hidden; }}
    .event-content {{ padding: 18px; }}
    img {{ display: block; width: 100%; height: auto; background: #000; }}
    .tags span {{ display: inline-block; margin: 4px 6px 0 0; padding: 4px 8px; background: #233044; border-radius: 999px; color: var(--accent); font-size: 12px; }}
  </style>
</head>
<body>
  <header>
    <h1>{html.escape(title)}</h1>
    <p>Generated by Panoptix. Mode: {html.escape(session.get("mode", ""))}. Started: {html.escape(session.get("started", ""))}</p>
  </header>
  <main>
    <section>
      <h2>Session Metadata</h2>
      <dl>{metadata_rows}</dl>
    </section>
    {self._render_highlight_section(highlight_cards)}
    <section>
      <h2>Evidence</h2>
      {cards}
    </section>
  </main>
</body>
</html>
"""

    @staticmethod
    def _render_highlight_section(highlight_cards: str) -> str:
        if not highlight_cards:
            return ""
        return f"""<section>
      <h2>Marked Highlights</h2>
      {highlight_cards}
    </section>"""

    def _render_event(self, session: dict, event: dict) -> str:
        image_src = self._image_data_url(session["id"], event["screenshot"])
        tags = "".join(f"<span>{html.escape(str(tag))}</span>" for tag in event.get("tags", []))
        note = event.get("staff_note") or event.get("note") or ""
        quote = event.get("cyp_quote") or ""
        return f"""<article class="event">
  <img src="{image_src}" alt="Evidence screenshot {event.get('index', '')}">
  <div class="event-content">
    <h3>{event.get('index', '')}. {html.escape(event.get('title') or event.get('type', 'Screenshot').title())}</h3>
    <p><strong>Time:</strong> {html.escape(event.get('timestamp', ''))}</p>
    <p>{html.escape(note)}</p>
    <p><em>{html.escape(quote)}</em></p>
    <div class="tags">{tags}</div>
  </div>
</article>"""

    def _image_data_url(self, session_id: str, filename: str) -> str:
        path = self.root / "sessions" / session_id / "screenshots" / filename
        encoded = base64.b64encode(path.read_bytes()).decode("ascii")
        return f"data:image/png;base64,{encoded}"


class PdfExporter:
    def __init__(self, root: Path):
        self.root = Path(root)
        self.store = SessionStore(self.root)

    def export(self, session_id: str) -> Path:
        try:
            from fpdf import FPDF
        except ImportError as exc:
            raise RuntimeError("fpdf2 is not installed; PDF export is unavailable") from exc

        session = self.store.load_session(session_id)
        output_dir = self.root / "exports" / session_id
        output_dir.mkdir(parents=True, exist_ok=True)
        output = output_dir / "evidence-report.pdf"
        metadata = session.get("metadata", {})
        title = metadata.get("activity") or "Panoptix Evidence Report"

        pdf = FPDF(unit="mm", format="A4")
        pdf.set_compression(False)
        pdf.set_auto_page_break(auto=True, margin=14)
        self._add_summary_page(pdf, session, title)
        if session.get("mode") == "observation":
            self._add_observation_pages(pdf, session)
        else:
            for event in session.get("events", []):
                self._add_event_page(pdf, session, event, title)
        pdf.output(str(output))
        return output

    def _add_summary_page(self, pdf, session: dict, title: str) -> None:
        metadata = session.get("metadata", {})
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 18)
        pdf.cell(0, 10, self._clean(title))
        pdf.ln(10)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, f"Generated by Panoptix | Mode: {session.get('mode', '')}")
        pdf.ln(8)
        pdf.cell(0, 8, f"Started: {session.get('started', '')}")
        pdf.ln(8)
        if session.get("stopped"):
            pdf.cell(0, 8, f"Stopped: {session.get('stopped')}")
            pdf.ln(8)
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, "Session metadata")
        pdf.ln(8)
        pdf.set_font("Helvetica", "", 11)
        page_width = pdf.w - pdf.l_margin - pdf.r_margin
        for key, value in metadata.items():
            if value:
                pdf.multi_cell(page_width, 7, f"{key.replace('_', ' ').title()}: {self._clean(str(value))}")

    def _add_event_page(self, pdf, session: dict, event: dict, title: str) -> None:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 14)
        heading = event.get("title") or event.get("type", "Screenshot").title()
        page_width = pdf.w - pdf.l_margin - pdf.r_margin
        pdf.multi_cell(page_width, 8, self._clean(f"{event.get('index', '')}. {heading}"))
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, self._clean(event.get("timestamp", "")))
        pdf.ln(6)
        image_path = self.root / "sessions" / session["id"] / "screenshots" / event["screenshot"]
        if image_path.exists():
            self._add_image(pdf, image_path)
        pdf.ln(4)
        pdf.set_font("Helvetica", "", 11)
        for label, key in (("Staff note", "staff_note"), ("CYP quote", "cyp_quote")):
            value = event.get(key)
            if value:
                pdf.set_font("Helvetica", "B", 11)
                pdf.cell(0, 6, label)
                pdf.ln(6)
                pdf.set_font("Helvetica", "", 11)
                pdf.multi_cell(page_width, 6, self._clean(str(value)))
        tags = event.get("tags") or []
        if tags:
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(page_width, 6, self._clean("Tags: " + ", ".join(str(tag) for tag in tags)))
        if event.get("highlight"):
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Marked as highlight")
            pdf.ln(6)

    def _add_observation_pages(self, pdf, session: dict) -> None:
        highlighted = [event for event in session.get("events", []) if event.get("highlight")]
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, "Highlights")
        pdf.ln(10)
        pdf.set_font("Helvetica", "", 11)
        if not highlighted:
            pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin, 7, "No screenshots were marked as highlights.")
        else:
            for event in highlighted:
                self._add_contact_sheet_item(pdf, session, event, include_note=True)

        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, "Observation Timeline")
        pdf.ln(10)
        pdf.set_font("Helvetica", "", 10)
        for event in session.get("events", []):
            if pdf.get_y() > 250:
                pdf.add_page()
                pdf.set_font("Helvetica", "B", 16)
                pdf.cell(0, 10, "Observation Timeline")
                pdf.ln(10)
                pdf.set_font("Helvetica", "", 10)
            self._add_contact_sheet_item(pdf, session, event, include_note=False)

    def _add_contact_sheet_item(self, pdf, session: dict, event: dict, include_note: bool) -> None:
        x = pdf.get_x()
        y = pdf.get_y()
        image_path = self.root / "sessions" / session["id"] / "screenshots" / event["screenshot"]
        if image_path.exists():
            self._add_thumbnail(pdf, image_path, x, y)
        pdf.set_xy(x + 48, y)
        title = event.get("title") or event.get("type", "Screenshot").title()
        marker = " [highlight]" if event.get("highlight") else ""
        pdf.set_font("Helvetica", "B", 10)
        pdf.multi_cell(130, 5, self._clean(f"{event.get('index', '')}. {title}{marker}"))
        pdf.set_x(x + 48)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(130, 5, self._clean(event.get("timestamp", "")))
        if include_note and event.get("staff_note"):
            pdf.set_x(x + 48)
            pdf.multi_cell(130, 5, self._clean(str(event["staff_note"])))
        pdf.set_y(max(pdf.get_y(), y + 34))
        pdf.ln(3)

    @staticmethod
    def _add_thumbnail(pdf, image_path: Path, x: float, y: float) -> None:
        try:
            pdf.image(str(image_path), x=x, y=y, w=42, h=30)
        except Exception:
            pdf.set_xy(x, y)
            pdf.set_font("Helvetica", "I", 8)
            pdf.multi_cell(42, 5, f"Image unavailable: {image_path.name}")
            pdf.set_xy(x, y)

    @staticmethod
    def _add_image(pdf, image_path: Path) -> None:
        try:
            from PIL import Image
        except ImportError:
            return
        try:
            with Image.open(image_path) as image:
                width_px, height_px = image.size
            page_width = pdf.w - pdf.l_margin - pdf.r_margin
            max_height = 145
            ratio = height_px / width_px if width_px else 1
            width = page_width
            height = width * ratio
            if height > max_height:
                height = max_height
                width = height / ratio if ratio else page_width
            pdf.image(str(image_path), w=width, h=height)
        except Exception:
            pdf.set_font("Helvetica", "I", 10)
            pdf.cell(0, 6, f"Screenshot could not be embedded: {image_path.name}")
            pdf.ln(6)

    @staticmethod
    def _clean(value: str) -> str:
        return value.encode("latin-1", errors="replace").decode("latin-1")


class SessionExporter:
    def __init__(self, root: Path):
        self.root = Path(root)

    def export(self, session_id: str) -> dict[str, Path]:
        return {
            "html": HtmlExporter(self.root).export(session_id),
            "pdf": PdfExporter(self.root).export(session_id),
        }
