from __future__ import annotations

import base64
import html
from pathlib import Path

from .storage import SessionStore


class HtmlExporter:
    def __init__(self, root: Path):
        self.root = Path(root)
        self.store = SessionStore(self.root)

    def export(self, session_id: str) -> Path:
        session = self.store.load_session(session_id)
        output_dir = self.root / "exports" / session_id
        output_dir.mkdir(parents=True, exist_ok=True)
        output = output_dir / "evidence-report.html"
        output.write_text(self._render(session), encoding="utf-8")
        return output

    def _render(self, session: dict) -> str:
        metadata = session.get("metadata", {})
        title = metadata.get("activity") or "Panoptix Evidence Report"
        cards = "\n".join(self._render_event(session, event) for event in session.get("events", []))
        metadata_rows = "\n".join(
            f"<dt>{html.escape(str(key).replace('_', ' ').title())}</dt><dd>{html.escape(str(value))}</dd>"
            for key, value in metadata.items()
            if value
        )
        return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{html.escape(title)}</title>
  <style>
    :root {{ --bg: #101318; --sur: #181d25; --text: #f5f7fa; --muted: #aab3c2; --accent: #4ade80; --danger: #ef233c; }}
    body {{ margin: 0; font-family: Arial, sans-serif; background: var(--bg); color: var(--text); }}
    header {{ padding: 28px 36px; border-bottom: 1px solid #2a313d; }}
    main {{ max-width: 1120px; margin: 0 auto; padding: 28px; }}
    dl {{ display: grid; grid-template-columns: 180px 1fr; gap: 8px 18px; color: var(--muted); }}
    dt {{ font-weight: 700; color: var(--text); }}
    .event {{ background: var(--sur); border: 1px solid #2a313d; border-radius: 8px; margin: 24px 0; overflow: hidden; }}
    .event-content {{ padding: 18px; }}
    img {{ display: block; width: 100%; height: auto; background: #000; }}
    .tags span {{ display: inline-block; margin: 4px 6px 0 0; padding: 4px 8px; background: #233044; border-radius: 999px; color: var(--accent); font-size: 12px; }}
  </style>
</head>
<body>
  <header>
    <h1>{html.escape(title)}</h1>
    <p>Generated by Panoptix. Mode: {html.escape(session.get("mode", ""))}. Started: {html.escape(session.get("started", ""))}</p>
  </header>
  <main>
    <section>
      <h2>Session Metadata</h2>
      <dl>{metadata_rows}</dl>
    </section>
    <section>
      <h2>Evidence</h2>
      {cards}
    </section>
  </main>
</body>
</html>
"""

    def _render_event(self, session: dict, event: dict) -> str:
        image_src = self._image_data_url(session["id"], event["screenshot"])
        tags = "".join(f"<span>{html.escape(str(tag))}</span>" for tag in event.get("tags", []))
        note = event.get("staff_note") or event.get("note") or ""
        quote = event.get("cyp_quote") or ""
        return f"""<article class="event">
  <img src="{image_src}" alt="Evidence screenshot {event.get('index', '')}">
  <div class="event-content">
    <h3>{event.get('index', '')}. {html.escape(event.get('title') or event.get('type', 'Screenshot').title())}</h3>
    <p><strong>Time:</strong> {html.escape(event.get('timestamp', ''))}</p>
    <p>{html.escape(note)}</p>
    <p><em>{html.escape(quote)}</em></p>
    <div class="tags">{tags}</div>
  </div>
</article>"""

    def _image_data_url(self, session_id: str, filename: str) -> str:
        path = self.root / "sessions" / session_id / "screenshots" / filename
        encoded = base64.b64encode(path.read_bytes()).decode("ascii")
        return f"data:image/png;base64,{encoded}"
