from pathlib import Path
from tempfile import TemporaryDirectory
import sys
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from panoptix_app.capture import PlaceholderCapture
from panoptix_app.exporter import HtmlExporter, SessionExporter
from panoptix_app.storage import SessionStore


class HtmlExporterTests(unittest.TestCase):
    def test_export_writes_self_contained_html_report(self):
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            store = SessionStore(root)
            session = store.create_session(
                "evidence",
                {"cyp": "AB", "activity": "Scratch game", "staff": "KS"},
                {},
            )
            screenshot = PlaceholderCapture().capture(
                root / "sessions" / session["id"] / "screenshots",
                "001.png",
            )
            store.add_event(
                session["id"],
                {
                    "type": "click",
                    "timestamp": "2026-05-28T10:00:00",
                    "screenshot": screenshot.name,
                    "x": 10,
                    "y": 20,
                    "title": "Opened Scratch",
                    "staff_note": "CYP selected the correct project.",
                    "cyp_quote": "I know where my game is.",
                    "tags": ["independent work"],
                },
            )

            output = HtmlExporter(root).export(session["id"])
            html = output.read_text(encoding="utf-8")

            self.assertIn("Scratch game", html)
            self.assertIn("Opened Scratch", html)
            self.assertIn("data:image/png;base64,", html)
            self.assertIn("independent work", html)

    def test_session_exporter_writes_html_and_pdf(self):
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            store = SessionStore(root)
            session = store.create_session(
                "evidence",
                {"cyp": "AB", "activity": "Scratch game", "staff": "KS"},
                {},
            )
            screenshot = PlaceholderCapture().capture(
                root / "sessions" / session["id"] / "screenshots",
                "001.png",
            )
            store.add_event(
                session["id"],
                {
                    "type": "click",
                    "timestamp": "2026-05-28T10:00:00",
                    "screenshot": screenshot.name,
                    "x": 10,
                    "y": 20,
                    "title": "Opened Scratch",
                    "staff_note": "CYP selected the correct project.",
                    "cyp_quote": "I know where my game is.",
                    "tags": ["independent work"],
                },
            )

            output = SessionExporter(root).export(session["id"])

            self.assertTrue(output["html"].exists())
            self.assertTrue(output["pdf"].exists())
            self.assertGreater(output["pdf"].stat().st_size, 500)

    def test_exports_include_staff_confirmation_and_page_footer(self):
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            store = SessionStore(root)
            session = store.create_session(
                "evidence",
                {"cyp": "AB", "activity": "Scratch game", "staff": "KS", "purpose": "UAS evidence"},
                {},
            )

            output = SessionExporter(root).export(session["id"])
            html = output["html"].read_text(encoding="utf-8")
            pdf_text = output["pdf"].read_bytes().decode("latin-1", errors="ignore")

            self.assertIn("Staff Confirmation", html)
            self.assertIn("Staff Confirmation", pdf_text)
            self.assertIn("Generated by Panoptix", pdf_text)

    def test_observation_pdf_uses_contact_sheet_layout(self):
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            store = SessionStore(root)
            session = store.create_session(
                "observation",
                {"cyp": "AB", "activity": "Long observation", "staff": "KS"},
                {},
            )
            screenshot_dir = root / "sessions" / session["id"] / "screenshots"
            for index in range(1, 8):
                screenshot = PlaceholderCapture().capture(screenshot_dir, f"{index:03d}.png")
                store.add_event(
                    session["id"],
                    {
                        "type": "periodic",
                        "timestamp": f"2026-05-28T10:0{index}:00",
                        "screenshot": screenshot.name,
                        "title": f"Observation {index}",
                        "staff_note": "",
                        "highlight": index in (2, 5),
                    },
                )

            output = SessionExporter(root).export(session["id"])
            pdf_text = output["pdf"].read_bytes().decode("latin-1", errors="ignore")
            html = output["html"].read_text(encoding="utf-8")

            self.assertIn("Observation Timeline", pdf_text)
            self.assertIn("Highlights", pdf_text)
            self.assertIn("Marked Highlights", html)


if __name__ == "__main__":
    unittest.main()
